import './js/multi-language';
import './js/utils/get-name-genres';
import './js/change-page';
import './js/btn-library';
import './js/search-movies';
import './js/modal-details';
import './js/open-close-modal-details';
import './js/pagination';
import './js/modal-team';
import './js/theme-switcher';

// import './js/api-service/get-trending-movies';
import './js/api-service/get-movies-by-key';
import './js/api-service/get-trailer';
// import './js/api-service/get-deatils';
import './js/api-service/get-genres';
import './js/render/render-pagination';
import './js/storage/storage';
import './js/refs/refs';
import './js/btn-library';
import './js/modal-details/watched';
import './js/to-top-btn';
import './js/storage/storage-settings';
